name: Validate Pull Request
on:
  pull_request:

concurrency:
  group: validate-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read # for the checkout action

jobs:
  lint-commits:
    name: Lint Commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Run Lint Commits Action
        uses: ./.github/actions/lint-commits
        with:
          from_ref: ${{ github.event.pull_request.base.sha }}
          to_ref: ${{ github.event.pull_request.head.sha }}

  check:
    name: Static Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - name: Install Node dependencies
        run: npm clean-install
      - name: Set up uv
        uses: astral-sh/setup-uv@v8
        with:
          enable-cache: true
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"
      - name: Install Python dependencies
        run: uv sync --locked
      - name: Check code style
        run: npm run style:check
      - name: Check syntax
        run: npm run syntax:check
      - name: Check package build
        run: npm run package:check

  test:
    name: Test Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - name: Install Node dependencies
        run: npm clean-install
      - name: Set up uv
        uses: astral-sh/setup-uv@v8
        with:
          enable-cache: true
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: uv sync --locked
      - name: Run tests
        run: npm run test
